on:
  push:
    branches:
      - main-disabled
jobs:
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    
    strategy:
      fail-fast: true
      matrix:
        php_version:
          - "8.4"
          - "8.5"
        variant:
          - ""
          - "-devcontainer"
          # Disabled for now
          # - "-hardened"
        alpine:
          - "3.23"
        frankenphp:
          - V1.11.1
    
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: clysec
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Login to CYCR
        uses: docker/login-action@v2
        with:
          registry: cycr.io
          username: ${{ secrets.CYCR_ACCOUNT }}
          password: ${{ secrets.CYCR_SECRET }}
  
      - name: Get PHP commit version
        id: php_commit_sha
        run: |
          cd base/php
          echo "PHP_COMMIT_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Prepare PHP Dockerfiles
        run: |
          cd base
          python3 generate.py ${{ matrix.variant }}

      - name: Prepare Depot
        uses: depot/setup-action@v1

      - name: Build and Push PHP ZTS Docker Image
        uses: depot/build-push-action@v1
        with:
          project: 35gblm93v9
          context: ./base/php/${{ matrix.php_version }}/alpine${{ matrix.alpine }}/zts
          file: ./base/php/${{ matrix.php_version }}/alpine${{ matrix.alpine }}/zts/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/clysec/php-zts:${{ matrix.php_version }}-alpine${{ matrix.alpine }}${{ matrix.variant }}
            ${{ (matrix.php_version == '8.4' && 'ghcr.io/clysec/php-zts:latest-alpine') || '' }}${{ (matrix.php_version == '8.4' && matrix.variant) || '' }}  
            docker.io/clysec/php-zts:${{ matrix.php_version }}-alpine${{ matrix.alpine }}${{ matrix.variant }}
            ${{ (matrix.php_version == '8.4' && 'docker.io/clysec/php-zts:latest-alpine') || '' }}${{ (matrix.php_version == '8.4' && matrix.variant) || '' }}
            cycr.io/clysec/php-zts:${{ matrix.php_version }}-alpine${{ matrix.alpine }}${{ matrix.variant }}
            ${{ (matrix.php_version == '8.4' && 'cycr.io/clysec/php-zts:latest-alpine') || '' }}${{ (matrix.php_version == '8.4' && matrix.variant) || '' }}

      - name: Build and Push FrankenPHP Docker Image
        uses: depot/build-push-action@v1
        with:
          project: 35gblm93v9
          context: ./frankenphp
          file: ./frankenphp/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          args: |
            PHP_VERSION=${{ matrix.php_version }}
            ALPINE_VERSION=${{ matrix.alpine }}
            VARIANT=${{ matrix.variant }}
            FRANKENPHP_VERSION=${{ matrix.frankenphp }}
          tags: |
            ghcr.io/clysec/frankenphp:${{ matrix.php_version }}-alpine${{ matrix.alpine }}${{ matrix.variant }}
            ${{ (matrix.php_version == '8.4' && 'ghcr.io/clysec/frankenphp:latest-alpine') || '' }}${{ (matrix.php_version == '8.4' && matrix.variant) || '' }}  
            docker.io/clysec/frankenphp:${{ matrix.php_version }}-alpine${{ matrix.alpine }}${{ matrix.variant }}
            ${{ (matrix.php_version == '8.4' && 'docker.io/clysec/frankenphp:latest-alpine') || '' }}${{ (matrix.php_version == '8.4' && matrix.variant) || '' }}  
            cycr.io/clysec/frankenphp:${{ matrix.php_version }}-alpine${{ matrix.alpine }}${{ matrix.variant }}
            ${{ (matrix.php_version == '8.4' && 'cycr.io/clysec/frankenphp:latest-alpine') || '' }}${{ (matrix.php_version == '8.4' && matrix.variant) || '' }}  
        
      - name: Build and Push Frankenpress Docker Image
        uses: depot/build-push-action@v1
        with:
          project: 35gblm93v9
          context: ./frankenpress
          file: ./frankenpress/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          args: |
            PHP_VERSION=${{ matrix.php_version }}
            ALPINE_VERSION=${{ matrix.alpine }}
            VARIANT=${{ matrix.variant }}
            FRANKENPHP_VERSION=${{ matrix.frankenphp }}
          tags: |
            ghcr.io/clysec/frankenpress:${{ matrix.php_version }}-alpine${{ matrix.alpine }}${{ matrix.variant }}
            ${{ (matrix.php_version == '8.4' && 'ghcr.io/clysec/frankenpress:latest-alpine') || '' }}${{ (matrix.php_version == '8.4' && matrix.variant) || '' }}  
            docker.io/clysec/frankenpress:${{ matrix.php_version }}-alpine${{ matrix.alpine }}${{ matrix.variant }}
            ${{ (matrix.php_version == '8.4' && 'docker.io/clysec/frankenpress:latest-alpine') || '' }}${{ (matrix.php_version == '8.4' && matrix.variant) || '' }}  
            cycr.io/clysec/frankenpress:${{ matrix.php_version }}-alpine${{ matrix.alpine }}${{ matrix.variant }}
            ${{ (matrix.php_version == '8.4' && 'cycr.io/clysec/frankenpress:latest-alpine') || '' }}${{ (matrix.php_version == '8.4' && matrix.variant) || '' }}